[package]
name = "peak-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
peak-core = { path = "../peak-core" }
peak-theme = { path = "../peak-theme" }
iced = { version = "0.13", features = ["tokio", "canvas", "advanced", "wgpu", "image", "svg", "lazy"] }
iced_widget = { version = "0.13", features = ["lazy"] }
tiny-skia = "0.11"



