[package]
name = "peak-ui"
version = "0.1.0"
edition = "2021"

[dependencies]
peak-core = { path = "../peak-core" }
iced = { version = "0.13", features = ["tokio", "canvas", "advanced", "wgpu", "image", "svg"] }
tiny-skia = "0.11"
