[workspace]

members = [
    "crates/peak-intelligence",
    "crates/peak-core",
    "crates/peak-desktop",
    "crates/peak-mobile",
    "crates/peak-browser", "crates/peak-ui", "crates/peak-apps",
]

resolver = "2"
