[package]
name = "peak-shell-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
[target.'cfg(target_os = "linux")'.dependencies]
wayland-server = "0.31"
wayland-client = "0.31"
wayland-protocols = { version = "0.31", features = ["staging"] }
wayland-scanner = "0.31"
